=== ingenmech/Task_8/devicesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices" elementFormDefault="qualified">
    <complexType name="AbstractComputerParts">
        <sequence>
            <element name="manufacturer" type="string"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" default="N/A"/>
    </complexType>
    <complexType name="Processor">
        <complexContent>
            <extension base="tns:AbstractComputerParts">
                <sequence>
                    <element name="frequencyCore" type="string"/>
                    <element name="coresNumber">
                        <simpleType>
                            <restriction base="int">
                                <pattern value="[1-8]{1,2}"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="processorType">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="GPU"/>
                                <enumeration value="CPU"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Board">
        <complexContent>
            <extension base="tns:AbstractComputerParts">
                <sequence>
                    <element name="type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="GAMING"/>
                                <enumeration value="PROFESSIONAL"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="MotherBoard">
        <complexContent>
            <extension base="tns:Board">
                <sequence>
                    <element name="configuration">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="eATX"/>
                                <enumeration value="mATX"/>
                                <enumeration value="ATX"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="processor" type="tns:Processor"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="VideoCard">
        <complexContent>
            <extension base="tns:Board">
                <sequence>
                    <element name="memoryRAM" type="string"/>
                    <element name="processor" type="tns:Processor"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <element name="parts" type="tns:AbstractComputerParts" abstract="true"/>
    <element name="board" type="tns:Board" substitutionGroup="tns:parts"/>
    <element name="motherBoard" type="tns:MotherBoard" substitutionGroup="tns:board"/>
    <element name="videoCard" type="tns:VideoCard" substitutionGroup="tns:board"/>
    <element name="processor" type="tns:Processor" substitutionGroup="tns:parts"/>
    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:parts" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
</schema>

=== ingenmech/Task_8/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation="http://www.example.com/devices devicesSchema.xsd">
    <motherBoard id="ID-1" name="MB_A1">
        <manufacturer>Asus</manufacturer>
        <type>PROFESSIONAL</type>
        <configuration>ATX</configuration>
        <processor id="ID-2" name="i7">
            <manufacturer>Intel</manufacturer>
            <frequencyCore>2100</frequencyCore>
            <coresNumber>4</coresNumber>
            <processorType>CPU</processorType>
        </processor>
    </motherBoard>
    <videoCard id="ID-3">
        <manufacturer>Asus</manufacturer>
        <type>GAMING</type>
        <memoryRAM>4</memoryRAM>
        <processor id="ID-4" name="i3">
            <manufacturer>NVIDIA</manufacturer>
            <frequencyCore>2100</frequencyCore>
            <coresNumber>4</coresNumber>
            <processorType>GPU</processorType>
        </processor>
    </videoCard>
    <motherBoard id="ID-5" name="ZEN_A1">
        <manufacturer>GIGABYTE</manufacturer>
        <type>GAMING</type>
        <configuration>mATX</configuration>
        <processor id="ID-6">
            <manufacturer>Intel</manufacturer>
            <frequencyCore>2100</frequencyCore>
            <coresNumber>4</coresNumber>
            <processorType>CPU</processorType>
        </processor>
    </motherBoard>
    <videoCard id="ID-7" name="VEGA">
        <manufacturer>AMD</manufacturer>
        <type>PROFESSIONAL</type>
        <memoryRAM>16</memoryRAM>
        <processor id="ID-8">
            <manufacturer>AMD</manufacturer>
            <frequencyCore>2100</frequencyCore>
            <coresNumber>4</coresNumber>
            <processorType>GPU</processorType>
        </processor>
    </videoCard>
    <processor id="ID-9" name="FX8300">
        <manufacturer>AMD</manufacturer>
        <frequencyCore>2100</frequencyCore>
        <coresNumber>4</coresNumber>
        <processorType>CPU</processorType>
    </processor>
    <processor id="ID-10" name="Ryzen3500">
        <manufacturer>AMD</manufacturer>
        <frequencyCore>2100</frequencyCore>
        <coresNumber>8</coresNumber>
        <processorType>CPU</processorType>
    </processor>
</devices>
