=== ingenmech/Task_8/src/test/resources/devicesSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.example.com/devices"
            xmlns:tns="http://www.example.com/devices" elementFormDefault="qualified">
    <element name="device" type="tns:AbstractComputerDevice" abstract="true"/>
    <element name="motherboard" type="tns:Motherboard" substitutionGroup="tns:device"/>
    <element name="video-card" type="tns:VideoCard" substitutionGroup="tns:device"/>
    <element name="processor" type="tns:Processor" substitutionGroup="tns:device"/>
    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="AbstractComputerDevice">
        <sequence>
            <element name="manufacturer" type="string"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="name" type="string" default="N/A"/>
    </complexType>
    <complexType name="Processor">
        <complexContent>
            <extension base="tns:AbstractComputerDevice">
                <sequence>
                    <element name="frequency-core" type="string"/>
                    <element name="cores-number">
                        <simpleType>
                            <restriction base="int">
                                <pattern value="[1-8]{1,2}"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="Motherboard">
        <complexContent>
            <extension base="tns:AbstractComputerDevice">
                <sequence>
                    <element name="configuration">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="E_ATX"/>
                                <enumeration value="M_ATX"/>
                                <enumeration value="ATX"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="nested-processor" type="tns:Processor"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="VideoCard">
        <complexContent>
            <extension base="tns:AbstractComputerDevice">
                <sequence>
                    <element name="memory-ram" type="int"/>
                    <element name="nested-processor" type="tns:Processor"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== ingenmech/Task_8/src/test/resources/devicesInvalid.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/devices"
         xsi:schemaLocation="http://www.example.com/devices devicesSchema.xsd">
    <motherboar id="ID-1" name="MB_A1">
        <manufacturer>Asus</manufacturer>
        <configuration>ATX</configuration>
        <nested-processor id="ID-2" name="i7">
            <manufacturer>Intel</manufacturer>
            <frequency-core>2100</frequency-core>
            <cores-number>4</cores-number>
        </nested-processor>
    </motherboar>
    <video-card id="ID-3">
        <manufacturer>Asus</manufacturer>
        <memory-ram>4</memory-ram>
        <nested-processor id="ID-4" name="Cuda">
            <manufacturer>NVIDIA</manufacturer>
            <frequency-core>2100</frequency-core>
            <cores-number>4</cores-number>
        </nested-processor>
    </video-card>
    <mothrboard id="ID-5" name="ZEN_A1">
        <manufacturer>GIGABYTE</manufacturer>
        <configuration>M_ATX</configuration>
        <nested-processor id="ID-6">
            <manufacturer>Intel</manufacturer>
            <frequency-core>2100</frequency-core>
            <cores-number>4</cores-number>
        </nested-processor>
    </mothrboard>
    <video-card id="ID-7" name="VEGA">
        <manufacturer>AMD</manufacturer>
        <memory-ram>16</memory-ram>
        <nested-processor id="ID-8">
            <manufacturer>AMD</manufacturer>
            <frequency-core>2100</frequency-core>
            <cores-number>4</cores-number>
        </nested-processor>
    </video-card>
    <processor id="ID-9" name="FX8300">
        <manufacturer>AMD</manufacturer>
        <frequency-core>2100</frequency-core>
        <cores-number>4</cores-number>
    </processor>
    <processor id="ID-10" name="Ryzen3500">
        <manufacturer>AMD</manufacturer>
        <frequency-core>2100</frequency-core>
        <cores-number>8</cores-number>
    </processor>
</devices>
